.class public abstract LQf/a$a;
.super Ljava/lang/Object;
.source "r8-map-id-a27a03ecaa04c3f144355334beb55c9cbfc36dda79e554423bceb24cf939fcb7"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = LQf/a;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "a"
.end annotation


# direct methods
.method public static a(LQf/a;I)[Ljava/lang/Object;
    .locals 0

    .line 1
    new-instance p0, LTd/s;

    .line 2
    .line 3
    const-string p1, "Generated by Android Extensions automatically"

    .line 4
    .line 5
    invoke-direct {p0, p1}, LTd/s;-><init>(Ljava/lang/String;)V

    .line 6
    .line 7
    .line 8
    throw p0
.end method
