package com.amazon.a.a.n.a;

/* JADX INFO: compiled from: r8-map-id-a27a03ecaa04c3f144355334beb55c9cbfc36dda79e554423bceb24cf939fcb7 */
/* JADX INFO: loaded from: classes3.dex */
public enum g {
    SLA_NO_CUSTOMER_ID,
    SLA_NO_DEVICE_ID,
    SLA_NO_LICENSE,
    CLA_LICENSE_EXPIRED,
    CLA_NOT_ENTITLED,
    CLA_LICENSE_INVALID,
    CLA_NO_CONTENT_ID,
    CLA_NO_DEVICE_ID,
    CLA_NO_VALID_LICENSE,
    CLA_NOT_LOGGED_IN,
    CLA_NULL_LOCKER_RESPONSE,
    CSA_CONTENT_MD_PKG_NAME_MISMATCH,
    CSA_INVALID_SIGNATURE,
    CSA_INVALID_CHECKSUM,
    CSA_NO_CONTENT_METADATA,
    VLA_NOT_LOGGED_IN,
    VLIA_NOT_LOGGED_IN
}
